import { invoke as invokeNative } from "@tauri-apps/api/core";
import type { AppConfiguration, BackupStorageOverview, BeyondCompareBundleInspection, BeyondCompareBundlePreview, BeyondCompareReadiness, BeyondCompareRecoveryPreview, CodexContentActionResult, CodexEnvironmentActionResult, CodexEnvironmentInput, CodexEnvironmentInstructions, CodexEnvironmentOverview, CodexMigrationArchives, CodexMigrationCreated, CodexMigrationGroup, CodexMigrationOverview, CodexMigrationPreview, CodexMigrationRestorePreview, CodexMigrationRestored, CodexPaths, CodexPetsOverview, CodexSkillsOverview, CompressionCommandPreview, CompressionConfig, CompressionReadiness, CompressionSourceTree, ConversationDiscovery, DeletePreview, DeleteResult, DiagnosticsSnapshot, FileTransferCommandPreview, FileTransferConfig, FileTransferDirectoryListing, FileTransferHistoryEntry, FileTransferReadiness, SourceTreeInspection, SourceTreePreview, SourceTreeReadiness, SourceTreeRecoveryPreview, XamppInspection, XamppPreview, XamppReadiness, XamppRecoveryPreview } from "../types/codex";

export const isTauriRuntime = () => typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
const browserPreviewConfiguration: AppConfiguration = { theme: "system", portableMode: false, createSafetyBackups: true, language: "en", logLevel: "warn", codexEnvironments: [], fileTransferProfiles: [] };
const browserPreviewDiagnostics: DiagnosticsSnapshot = { operatingSystem: "unknown", architecture: "Browser preview", codexHome: "—", codexHomeExists: false, configDir: "—", backupDir: "—", codexCliVersion: null, skillsCount: 0, petsCount: 0 };
const browserPreviewBackupStorage: BackupStorageOverview = { sessionBackups: { directory: "—", fileCount: 0, totalBytes: 0, recentFiles: [] }, personalBundles: { directory: "—", fileCount: 0, totalBytes: 0, recentFiles: [] } };
const invoke = <T>(command: string, args?: Record<string, unknown>): Promise<T> => isTauriRuntime() ? invokeNative<T>(command, args) : Promise.reject(new Error("Native actions are available only in the Dev Companion desktop app."));

export const getDiagnostics = (): Promise<DiagnosticsSnapshot> => isTauriRuntime() ? invoke("get_diagnostics") : Promise.resolve(browserPreviewDiagnostics);
export const getBackupStorage = (): Promise<BackupStorageOverview> => isTauriRuntime() ? invoke("get_backup_storage") : Promise.resolve(browserPreviewBackupStorage);
export const getSkills = (): Promise<CodexSkillsOverview> => invoke("get_skills");
export const importSkill = (): Promise<CodexContentActionResult | null> => invoke("import_skill");
export const exportSkill = (id: string): Promise<CodexContentActionResult | null> => invoke("export_skill", { id });
export const getPets = (): Promise<CodexPetsOverview> => invoke("get_pets");
export const installPet = (): Promise<CodexContentActionResult | null> => invoke("install_pet");
export const removePet = (id: string, confirmation: string): Promise<CodexContentActionResult> => invoke("remove_pet", { id, confirmation });
export const getPaths = (): Promise<CodexPaths> => invoke("get_codex_paths");
export const discoverConversations = (): Promise<ConversationDiscovery> => invoke("discover_conversations");
export const previewLocalDelete = (selectedIds: string[]): Promise<DeletePreview> => invoke("preview_local_delete", { selectedIds });
export const executeLocalDelete = (selectedIds: string[], confirmation: string): Promise<DeleteResult> => invoke("execute_local_delete", { selectedIds, confirmation });
export const getBeyondCompareReadiness = (): Promise<BeyondCompareReadiness> => invoke("get_beyond_compare_readiness");
export const previewBeyondCompare = (credentialsIncluded: boolean): Promise<BeyondCompareBundlePreview | null> => invoke("preview_beyond_compare", { credentialsIncluded });
export const createBeyondCompareBundle = (token: string): Promise<{ bundleName: string; bytes: number }> => invoke("create_beyond_compare_bundle", { token });
export const inspectBeyondCompareBundle = (): Promise<BeyondCompareBundleInspection | null> => invoke("inspect_beyond_compare_bundle");
export const previewBeyondCompareRecovery = (token: string): Promise<BeyondCompareRecoveryPreview> => invoke("preview_beyond_compare_recovery", { token });
export const recoverBeyondCompare = (token: string, confirmation: string): Promise<{ recovered: boolean; stagingPath: string }> => invoke("recover_beyond_compare", { token, confirmation });
export const getSourceTreeReadiness = (): Promise<SourceTreeReadiness> => invoke("get_sourcetree_readiness");
export const previewSourceTree = (): Promise<SourceTreePreview> => invoke("preview_sourcetree");
export const createSourceTreeBundle = (token: string): Promise<{ bundleName: string; bytes: number }> => invoke("create_sourcetree_bundle", { token });
export const inspectSourceTreeBundle = (): Promise<SourceTreeInspection | null> => invoke("inspect_sourcetree_bundle");
export const previewSourceTreeRecovery = (token: string): Promise<SourceTreeRecoveryPreview> => invoke("preview_sourcetree_recovery", { token });
export const recoverSourceTree = (token: string, confirmation: string): Promise<{ recovered: boolean; stagingPath: string; manualOnly: boolean }> => invoke("recover_sourcetree", { token, confirmation });
export const previewSourceTreeConfig = (): Promise<import("../types/codex").SourceTreeConfigPreview> => invoke("preview_sourcetree_config");
export const createSourceTreeConfigBundle = (token: string, password: string): Promise<{ bundleName: string; bundlePath: string; bytes: number }> => invoke("create_sourcetree_config_bundle", { token, password });
export const openSourceTreeConfigBundleFolder = (): Promise<void> => invoke("open_sourcetree_config_bundle_folder");
export const listSourceTreeConfigArchives = (): Promise<import("../types/codex").SourceTreeConfigArchives> => invoke("list_sourcetree_config_archives");
export const openSourceTreeConfigArchive = (name: string): Promise<void> => invoke("open_sourcetree_config_archive", { name });
export const deleteSourceTreeConfigArchive = (name: string): Promise<void> => invoke("delete_sourcetree_config_archive", { name });
export const inspectSourceTreeConfigArchive = (name: string, password: string): Promise<import("../types/codex").SourceTreeConfigInspection> => invoke("inspect_sourcetree_config_archive", { name, password });
export const inspectSourceTreeConfigBundle = (password: string): Promise<import("../types/codex").SourceTreeConfigInspection | null> => invoke("inspect_sourcetree_config_bundle", { password });
export const previewSourceTreeConfigRecovery = (token: string, password: string): Promise<import("../types/codex").SourceTreeConfigRecoveryPreview> => invoke("preview_sourcetree_config_recovery", { token, password });
export const recoverSourceTreeConfig = (token: string, confirmation: string, password: string): Promise<import("../types/codex").SourceTreeConfigRecoveryResult> => invoke("recover_sourcetree_config", { token, confirmation, password });
export const deleteSourceTreeConfigBundle = (token: string, confirmation: string): Promise<void> => invoke("delete_sourcetree_config_bundle", { token, confirmation });
export const getXamppReadiness = (): Promise<XamppReadiness> => invoke("get_xampp_readiness");
export const previewXampp = (): Promise<XamppPreview | null> => invoke("preview_xampp");
export const createXamppBundle = (token: string): Promise<{ bundleName: string; bytes: number }> => invoke("create_xampp_bundle", { token });
export const inspectXamppBundle = (): Promise<XamppInspection | null> => invoke("inspect_xampp_bundle");
export const previewXamppRecovery = (token: string): Promise<XamppRecoveryPreview> => invoke("preview_xampp_recovery", { token });
export const recoverXampp = (token: string, confirmation: string): Promise<{ recovered: boolean; stagingPath: string; manualOnly: boolean }> => invoke("recover_xampp", { token, confirmation });
export const getConfiguration = (): Promise<AppConfiguration> => isTauriRuntime() ? invoke("get_configuration") : Promise.resolve(browserPreviewConfiguration);
export const saveConfiguration = (configuration: AppConfiguration): Promise<void> =>
  isTauriRuntime() ? invoke("save_configuration", { configuration }) : Promise.resolve();
export const getCodexEnvironmentOverview = (): Promise<CodexEnvironmentOverview> => invoke("get_codex_environment_overview");
export const saveCodexEnvironment = (input: CodexEnvironmentInput) => invoke("save_codex_environment", { input });
export const regenerateCodexLauncher = (id: string): Promise<CodexEnvironmentActionResult> => invoke("regenerate_codex_launcher", { id });
export const removeCodexLauncher = (id: string, confirmation: string): Promise<CodexEnvironmentActionResult> => invoke("remove_codex_launcher", { id, confirmation });
export const addCodexLauncherDirToUserPath = (): Promise<CodexEnvironmentActionResult> => invoke("add_codex_launcher_dir_to_user_path");
export const getCodexEnvironmentInstructions = (id: string): Promise<CodexEnvironmentInstructions> => invoke("get_codex_environment_instructions", { id });
export const updateCodexEnvironmentInstructions = (id: string, content: string): Promise<CodexEnvironmentActionResult> => invoke("update_codex_environment_instructions", { id, content });
export const deleteCodexEnvironment = (id: string, confirmation: string): Promise<CodexEnvironmentActionResult> => invoke("delete_codex_environment", { id, confirmation });
export const openCodexEnvironmentHome = (id: string): Promise<CodexEnvironmentActionResult> => invoke("open_codex_environment_home", { id });
export const openCodexEnvironmentAgents = (id: string): Promise<CodexEnvironmentActionResult> => invoke("open_codex_environment_agents", { id });
export const runCodexEnvironmentAction = (id: string, action: "launch" | "login" | "logout"): Promise<CodexEnvironmentActionResult> => invoke("run_codex_environment_action", { id, action });
export const getCodexMigrationOverview = (): Promise<CodexMigrationOverview> => invoke("get_codex_migration_overview");
export const previewCodexMigration = (accountIds: string[], groups: CodexMigrationGroup[]): Promise<CodexMigrationPreview> => invoke("preview_codex_migration", { accountIds, groups });
export const createCodexMigration = (token: string): Promise<CodexMigrationCreated> => invoke("create_codex_migration", { token });
export const listCodexMigrationArchives = (): Promise<CodexMigrationArchives> => invoke("list_codex_migration_archives");
export const openCodexMigrationArchive = (name: string): Promise<void> => invoke("open_codex_migration_archive", { name });
export const deleteCodexMigrationArchive = (name: string): Promise<void> => invoke("delete_codex_migration_archive", { name });
export const inspectCodexMigrationArchive = (name: string): Promise<CodexMigrationPreview> => invoke("inspect_codex_migration_archive", { name });
export const inspectCodexMigration = (): Promise<CodexMigrationPreview | null> => invoke("inspect_codex_migration");
export const previewCodexMigrationRestore = (token: string): Promise<CodexMigrationRestorePreview> => invoke("preview_codex_migration_restore", { token });
export const restoreCodexMigration = (token: string, confirmation: string, replaceChat: boolean): Promise<CodexMigrationRestored> => invoke("restore_codex_migration", { token, confirmation, replaceChat });
export const stopCodexProcesses = (): Promise<import("../types/codex").CodexProcessResult> => invoke("stop_codex_processes", { confirmation: "CLOSE CODEX" });
export const getFileTransferReadiness = (): Promise<FileTransferReadiness> => invoke("get_file_transfer_readiness");
export const listFileTransferDirectory = (path: string): Promise<FileTransferDirectoryListing> => invoke("list_file_transfer_directory", { path });
const fileTransferPayload = (config: FileTransferConfig): FileTransferConfig => ({ ...config, includeSubfolders: config.includeSubfolders === true, preserveTimestamps: config.preserveTimestamps === true, skipJunctionPoints: config.skipJunctionPoints === true, restartable: config.restartable === true, copyEmptyDirectories: config.copyEmptyDirectories === true, verifyDestination: config.verifyDestination === true, saveLog: config.saveLog === true, shutdownWhenFinished: config.shutdownWhenFinished === true, selectionEnabled: config.selectionEnabled === true, mirrorConfirmed: config.mirrorConfirmed === true, systemLocationConfirmed: config.systemLocationConfirmed === true, destinationDataConfirmed: config.destinationDataConfirmed === true });
export const previewFileTransfer = (config: FileTransferConfig): Promise<FileTransferCommandPreview> => invoke("preview_file_transfer", { config: fileTransferPayload(config) });
export const pickFileTransferFolder = (title: string): Promise<string | null> => invoke("pick_file_transfer_folder", { title });
export const startFileTransfer = (config: FileTransferConfig, analyze: boolean, progressTotalBytes: number | null = null) => invoke("start_file_transfer", { config: fileTransferPayload(config), analyze: analyze === true, progressTotalBytes });
export const cancelFileTransfer = (): Promise<void> => invoke("cancel_file_transfer");
export const getFileTransferHistory = (): Promise<FileTransferHistoryEntry[]> => invoke("get_file_transfer_history");
export const openFileTransferLog = (path: string): Promise<void> => invoke("open_file_transfer_log", { path });
export const deleteFileTransferLog = (id: string): Promise<void> => invoke("delete_file_transfer_log", { id });
export const openFileTransferLogsFolder = (): Promise<void> => invoke("open_file_transfer_logs_folder");
export const getCompressionReadiness = (): Promise<CompressionReadiness> => invoke("get_compression_readiness");
export const scanCompressionSource = (source: string): Promise<CompressionSourceTree> => invoke("scan_compression_source", { source });
export const pickCompressionFolder = (title: string): Promise<string | null> => invoke("pick_compression_folder", { title });
export const previewCompression = (config: CompressionConfig): Promise<CompressionCommandPreview> => invoke("preview_compression", { config });
export const startCompression = (config: CompressionConfig): Promise<{ state: string }> => invoke("start_compression", { config });
export const cancelCompression = (): Promise<void> => invoke("cancel_compression");
