import { invoke } from "@tauri-apps/api/core";
import type { AppConfiguration, ArchiveInspection, BackupPreview, BackupResult, BeyondCompareBundleInspection, BeyondCompareBundlePreview, BeyondCompareReadiness, BeyondCompareRecoveryPreview, CodexPaths, ConversationDiscovery, DeletePreview, DeleteResult, DiagnosticsSnapshot, FileTransferCommandPreview, FileTransferConfig, FileTransferDirectoryListing, FileTransferHistoryEntry, FileTransferReadiness, RestoreHistoryEntry, RestorePreview, RestoreResult, SourceTreeInspection, SourceTreePreview, SourceTreeReadiness, SourceTreeRecoveryPreview, XamppInspection, XamppPreview, XamppReadiness, XamppRecoveryPreview } from "../types/codex";

export const getDiagnostics = (): Promise<DiagnosticsSnapshot> => invoke("get_diagnostics");
export const getPaths = (): Promise<CodexPaths> => invoke("get_codex_paths");
export const discoverConversations = (): Promise<ConversationDiscovery> => invoke("discover_conversations");
export const previewBackup = (selectedIds: string[]): Promise<BackupPreview> => invoke("preview_backup", { selectedIds });
export const createBackup = (selectedIds: string[]): Promise<BackupResult> => invoke("create_backup", { selectedIds });
export const inspectBackupArchive = (): Promise<ArchiveInspection | null> => invoke("inspect_backup_archive");
export const previewRestore = (restoreToken: string, selectedIds: string[]): Promise<RestorePreview> => invoke("preview_restore", { restoreToken, selectedIds });
export const restoreArchive = (restoreToken: string, selectedIds: string[]): Promise<RestoreResult> => invoke("restore_archive", { restoreToken, selectedIds });
export const getRestoreHistory = (): Promise<RestoreHistoryEntry[]> => invoke("get_restore_history");
export const previewLocalDelete = (selectedIds: string[]): Promise<DeletePreview> => invoke("preview_local_delete", { selectedIds });
export const executeLocalDelete = (selectedIds: string[], confirmation: string): Promise<DeleteResult> => invoke("execute_local_delete", { selectedIds, confirmation });
export const getBeyondCompareReadiness = (): Promise<BeyondCompareReadiness> => invoke("get_beyond_compare_readiness");
export const previewBeyondCompare = (credentialsIncluded: boolean): Promise<BeyondCompareBundlePreview | null> => invoke("preview_beyond_compare", { credentialsIncluded });
export const createBeyondCompareBundle = (token: string): Promise<{ bundleName: string; bytes: number }> => invoke("create_beyond_compare_bundle", { token });
export const inspectBeyondCompareBundle = (): Promise<BeyondCompareBundleInspection | null> => invoke("inspect_beyond_compare_bundle");
export const previewBeyondCompareRecovery = (token: string): Promise<BeyondCompareRecoveryPreview> => invoke("preview_beyond_compare_recovery", { token });
export const recoverBeyondCompare = (token: string, confirmation: string): Promise<{ recovered: boolean; stagingPath: string }> => invoke("recover_beyond_compare", { token, confirmation });
export const getSourceTreeReadiness = (): Promise<SourceTreeReadiness> => invoke("get_sourcetree_readiness");
export const previewSourceTree = (): Promise<SourceTreePreview> => invoke("preview_sourcetree");
export const createSourceTreeBundle = (token: string): Promise<{ bundleName: string; bytes: number }> => invoke("create_sourcetree_bundle", { token });
export const inspectSourceTreeBundle = (): Promise<SourceTreeInspection | null> => invoke("inspect_sourcetree_bundle");
export const previewSourceTreeRecovery = (token: string): Promise<SourceTreeRecoveryPreview> => invoke("preview_sourcetree_recovery", { token });
export const recoverSourceTree = (token: string, confirmation: string): Promise<{ recovered: boolean; stagingPath: string; manualOnly: boolean }> => invoke("recover_sourcetree", { token, confirmation });
export const getXamppReadiness = (): Promise<XamppReadiness> => invoke("get_xampp_readiness");
export const previewXampp = (): Promise<XamppPreview | null> => invoke("preview_xampp");
export const createXamppBundle = (token: string): Promise<{ bundleName: string; bytes: number }> => invoke("create_xampp_bundle", { token });
export const inspectXamppBundle = (): Promise<XamppInspection | null> => invoke("inspect_xampp_bundle");
export const previewXamppRecovery = (token: string): Promise<XamppRecoveryPreview> => invoke("preview_xampp_recovery", { token });
export const recoverXampp = (token: string, confirmation: string): Promise<{ recovered: boolean; stagingPath: string; manualOnly: boolean }> => invoke("recover_xampp", { token, confirmation });
export const getConfiguration = (): Promise<AppConfiguration> => invoke("get_configuration");
export const saveConfiguration = (configuration: AppConfiguration): Promise<void> =>
  invoke("save_configuration", { configuration });
export const getFileTransferReadiness = (): Promise<FileTransferReadiness> => invoke("get_file_transfer_readiness");
export const listFileTransferDirectory = (path: string): Promise<FileTransferDirectoryListing> => invoke("list_file_transfer_directory", { path });
const fileTransferPayload = (config: FileTransferConfig): FileTransferConfig => ({ ...config, includeSubfolders: config.includeSubfolders === true, preserveTimestamps: config.preserveTimestamps === true, skipJunctionPoints: config.skipJunctionPoints === true, restartable: config.restartable === true, copyEmptyDirectories: config.copyEmptyDirectories === true, verifyDestination: config.verifyDestination === true, saveLog: config.saveLog === true, shutdownWhenFinished: config.shutdownWhenFinished === true, selectionEnabled: config.selectionEnabled === true, mirrorConfirmed: config.mirrorConfirmed === true, systemLocationConfirmed: config.systemLocationConfirmed === true, destinationDataConfirmed: config.destinationDataConfirmed === true });
export const previewFileTransfer = (config: FileTransferConfig): Promise<FileTransferCommandPreview> => invoke("preview_file_transfer", { config: fileTransferPayload(config) });
export const pickFileTransferFolder = (title: string): Promise<string | null> => invoke("pick_file_transfer_folder", { title });
export const startFileTransfer = (config: FileTransferConfig, analyze: boolean) => invoke("start_file_transfer", { config: fileTransferPayload(config), analyze });
export const cancelFileTransfer = (): Promise<void> => invoke("cancel_file_transfer");
export const getFileTransferHistory = (): Promise<FileTransferHistoryEntry[]> => invoke("get_file_transfer_history");
export const openFileTransferLog = (path: string): Promise<void> => invoke("open_file_transfer_log", { path });
export const openFileTransferLogsFolder = (): Promise<void> => invoke("open_file_transfer_logs_folder");
