import { selectionMatches } from "../../utils/safety";
import { useCallback, useMemo, useState } from "react";
import { PageHeader } from "../../components/PageHeader";
import { useTranslation, type TranslationKey } from "../../i18n";
import { useAsyncValue } from "../../hooks/useAsyncValue";
import { discoverConversations, executeLocalDelete, previewLocalDelete } from "../../services/tauri";
import type { ConversationDiscoveryStatus, ConversationSummary, DeletePreview, DeleteResult } from "../../types/codex";

type SortOrder = "updated" | "created" | "title" | "project";
const statusKeys: Record<Exclude<ConversationDiscoveryStatus, "ready">, TranslationKey> = { codexHomeMissing: "conversations.unavailableHome", sessionDirectoryMissing: "conversations.unavailableDirectory", permissionDenied: "conversations.unavailablePermission", filesystemUnavailable: "conversations.unavailableFilesystem" };
const compareText = (left: string | null, right: string | null) => (left ?? "").localeCompare(right ?? "");
const formatBytes = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;

export function ConversationsPage() {
  const { t, language } = useTranslation();
  const discovery = useAsyncValue(useCallback(() => discoverConversations(), []));
  const [query, setQuery] = useState(""); const [project, setProject] = useState("all"); const [sort, setSort] = useState<SortOrder>("updated");
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [deletePreview, setDeletePreview] = useState<DeletePreview | null>(null); const [previewIds, setPreviewIds] = useState<string[]>([]); const [confirmation, setConfirmation] = useState(""); const [deleting, setDeleting] = useState(false); const [deleteResult, setDeleteResult] = useState<DeleteResult | null>(null); const [deleteError, setDeleteError] = useState<string | null>(null);
  const projects = useMemo(() => [...new Set((discovery.value?.conversations ?? []).map((item) => item.projectPath).filter((value): value is string => Boolean(value)))].sort(), [discovery.value]);
  const conversations = useMemo(() => [...(discovery.value?.conversations ?? [])].filter((item) => project === "all" || item.projectPath === project).filter((item) => !query.trim() || [item.title, item.projectName, item.projectPath, item.id].some((value) => value?.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()))).sort((left, right) => sort === "title" ? compareText(left.title, right.title) : sort === "project" ? compareText(left.projectName, right.projectName) : compareText(right[sort === "updated" ? "updatedAt" : "createdAt"], left[sort === "updated" ? "updatedAt" : "createdAt"])), [discovery.value, project, query, sort]);
  const selectedIds = useMemo(() => [...selected].sort(), [selected]); const previewCurrent = deletePreview !== null && selectionMatches(previewIds, selectedIds);
  const dateFormatter = useMemo(() => new Intl.DateTimeFormat(language, { dateStyle: "medium", timeStyle: "short" }), [language]);
  const formatDate = (value: string | null) => {
    const date = value ? new Date(value) : null;
    return date === null || Number.isNaN(date.valueOf()) ? t("common.dash") : dateFormatter.format(date);
  };
  const toggle = (id: string) => { setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); setDeletePreview(null); setDeleteResult(null); setConfirmation(""); };
  const makePreview = async () => { setDeleting(true); setDeleteError(null); try { setDeletePreview(await previewLocalDelete(selectedIds)); setPreviewIds(selectedIds); setConfirmation(""); setDeleteResult(null); } catch { setDeletePreview(null); setDeleteError(t("conversations.deleteError")); } finally { setDeleting(false); } };
  const execute = async () => { setDeleting(true); setDeleteError(null); try { const result = await executeLocalDelete(selectedIds, confirmation); setDeleteResult(result); if (result.outcome === "completed") { setSelected(new Set()); setDeletePreview(null); setConfirmation(""); await discovery.refresh(); } } catch { setDeleteError(t("conversations.deleteError")); } finally { setDeleting(false); } };
  return <>
    <PageHeader title={t("conversations.title")} description={t("conversations.description")} action={<button type="button" onClick={() => void discovery.refresh()} disabled={discovery.loading || deleting}>{discovery.loading ? t("common.refreshing") : t("common.refresh")}</button>} />
    {discovery.error && <p className="error-banner">{t("conversations.discoveryError", { error: discovery.error })}</p>}{deleteError && <p className="error-banner">{deleteError}</p>}
    {discovery.value && discovery.value.status !== "ready" && <section className="notice-card"><h2>{t("conversations.unavailableTitle")}</h2><p>{t(statusKeys[discovery.value.status])}</p></section>}
    {discovery.value?.status === "ready" && <>
      <div className="summary-grid conversation-summary"><article className="summary-card"><span>{t("conversations.found")}</span><strong>{discovery.value.totalDiscovered}</strong></article><article className="summary-card"><span>{t("conversations.ready")}</span><strong>{discovery.value.successfullyParsed}</strong></article><article className="summary-card"><span>{t("conversations.skipped")}</span><strong>{discovery.value.skipped}</strong></article><article className="summary-card"><span>{t("conversations.unsupported")}</span><strong>{discovery.value.unsupported}</strong></article></div>
      <section className="conversation-controls" aria-label={t("conversations.filters")}><label>{t("conversations.search")}<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("conversations.searchPlaceholder")} /></label><label>{t("conversations.project")}<select value={project} onChange={(event) => setProject(event.target.value)}><option value="all">{t("conversations.allProjects")}</option>{projects.map((path) => <option key={path} value={path}>{path}</option>)}</select></label><label>{t("conversations.sort")}<select value={sort} onChange={(event) => setSort(event.target.value as SortOrder)}><option value="updated">{t("conversations.updated")}</option><option value="created">{t("conversations.created")}</option><option value="title">{t("conversations.titleColumn")}</option><option value="project">{t("conversations.project")}</option></select></label></section>
      {conversations.length === 0 ? <section className="notice-card"><h2>{discovery.value.totalDiscovered === 0 ? t("conversations.noSessions") : t("conversations.noMatching")}</h2><p>{discovery.value.totalDiscovered === 0 ? t("conversations.noSessionsDescription") : t("conversations.noMatchingDescription")}</p></section> : <><section className="delete-selection"><div><h2>{t("conversations.selectedDelete", { count: selectedIds.length })}</h2><p>{t("conversations.deleteScope")}</p></div><button type="button" className="danger-button" onClick={() => void makePreview()} disabled={deleting || selectedIds.length === 0}>{t("conversations.previewDelete")}</button></section><section className="conversation-table-wrap"><table className="conversation-table"><thead><tr><th>{t("conversations.selectDelete")}</th><th>{t("conversations.titleColumn")}</th><th>{t("conversations.project")}</th><th>{t("conversations.updated")}</th><th>{t("conversations.created")}</th><th>{t("conversations.source")}</th></tr></thead><tbody>{conversations.map((conversation) => <ConversationRow key={conversation.id} conversation={conversation} disabled={deleting} checked={selected.has(conversation.id)} onToggle={toggle} formatDate={formatDate} />)}</tbody></table></section></>}
      {deletePreview && previewCurrent && <section className="delete-preview" aria-live="polite"><h2>{t("conversations.deletePreview")}</h2><p>{t("conversations.deleteScope")}</p><dl><div><dt>{t("conversations.deleteFiles")}</dt><dd>{deletePreview.sessionCount} · {formatBytes(deletePreview.totalBytes)}</dd></div><div><dt>{t("conversations.quarantine")}</dt><dd><code>{deletePreview.quarantineDirectory}</code></dd></div></dl><p>{t("conversations.deleteSafety")}</p><ul className="safe-session-list">{deletePreview.sessions.map((session) => <li key={session.id}><strong>{session.title || t("conversations.untitled")}</strong><code>{session.id} · {formatBytes(session.bytes)}</code></li>)}</ul><label className="delete-confirmation">{t("conversations.confirmDelete")}<input aria-label={t("conversations.confirmDelete")} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" /></label><button type="button" className="danger-button" onClick={() => void execute()} disabled={deleting || confirmation !== "DELETE"}>{t("conversations.executeDelete")}</button></section>}
      {deleteResult && <section className={deleteResult.outcome === "completed" ? "success-card" : deleteResult.outcome === "rolledBack" ? "partial-card" : "error-card"}><h2>{deleteResult.outcome === "completed" ? t("conversations.deleteCompleted") : deleteResult.outcome === "rolledBack" ? t("conversations.deleteRolledBack") : t("conversations.deleteFailed")}</h2><p>{t("conversations.deleteSummary", { deleted: deleteResult.deletedCount, restored: deleteResult.restoredCount, skipped: deleteResult.skippedCount })}</p>{deleteResult.safetyArchivePath && <code>{deleteResult.safetyArchivePath}</code>}</section>}
    </>}
  </>;
}

function ConversationRow({ conversation, disabled, checked, onToggle, formatDate }: { conversation: ConversationSummary; disabled: boolean; checked: boolean; onToggle: (id: string) => void; formatDate: (value: string | null) => string }) {
  const { t } = useTranslation();
  return <tr><td><input type="checkbox" disabled={disabled} aria-label={`${t("conversations.selectDelete")}: ${conversation.id}`} checked={checked} onChange={() => onToggle(conversation.id)} /></td><td><strong>{conversation.title || t("conversations.untitled")}</strong><code>{conversation.id}</code></td><td><span>{conversation.projectName || t("common.dash")}</span>{conversation.projectPath && <code>{conversation.projectPath}</code>}</td><td>{formatDate(conversation.updatedAt)}</td><td>{formatDate(conversation.createdAt)}</td><td>{conversation.source || t("common.dash")}</td></tr>;
}
