import { useState } from "react";
import { PageHeader } from "../../components/PageHeader";
import { useTranslation } from "../../i18n";
import { createSourceTreeConfigBundle, deleteSourceTreeConfigBundle, inspectSourceTreeConfigBundle, openSourceTreeConfigBundleFolder, previewSourceTreeConfig, previewSourceTreeConfigRecovery, recoverSourceTreeConfig } from "../../services/tauri";
import type { SourceTreeConfigInspection, SourceTreeConfigPreview, SourceTreeConfigRecoveryPreview } from "../../types/codex";

export function SourceTreePage() {
  const { t } = useTranslation();
  const [preview, setPreview] = useState<SourceTreeConfigPreview | null>(null); const [inspection, setInspection] = useState<SourceTreeConfigInspection | null>(null); const [recovery, setRecovery] = useState<SourceTreeConfigRecoveryPreview | null>(null); const [createPassword, setCreatePassword] = useState(""); const [createPasswordConfirmation, setCreatePasswordConfirmation] = useState(""); const [restorePassword, setRestorePassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [deleteConfirmation, setDeleteConfirmation] = useState(""); const [result, setResult] = useState(""); const [resultTitle, setResultTitle] = useState<"sourceTreeConfig.bundleCreated" | "sourceTreeConfig.restored">("sourceTreeConfig.bundleCreated"); const [restored, setRestored] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); } catch (reason) { setError(typeof reason === "string" ? reason : reason instanceof Error ? reason.message : t("sourceTreeConfig.error")); } finally { setBusy(false); } };
  const list = (files: { name: string; bytes: number }[]) => <ul>{files.map((file) => <li key={file.name}><code>{file.name}</code> · {file.bytes} bytes</li>)}</ul>;
  const passwordReady = Array.from(createPassword).length >= 12 && createPassword === createPasswordConfirmation;
  return <>
    <PageHeader title={t("sourceTree.title")} description={t("sourceTreeConfig.description")} />
    <section className="notice-card"><h2>{t("sourceTreeConfig.title")}</h2><p>{t("sourceTreeConfig.description")}</p><p>{t("sourceTreeConfig.encryption")}</p></section>
    <section className="backup-preview"><h2>{t("sourceTreeConfig.files")}</h2><label className="delete-confirmation">{t("sourceTreeConfig.createPassword")}<input type="password" autoComplete="new-password" disabled={busy} value={createPassword} onChange={(event) => setCreatePassword(event.target.value)} /></label><label className="delete-confirmation">{t("sourceTreeConfig.confirmPassword")}<input type="password" autoComplete="new-password" disabled={busy} value={createPasswordConfirmation} onChange={(event) => setCreatePasswordConfirmation(event.target.value)} /></label><p>{t("sourceTreeConfig.passwordMinimum")}</p><button disabled={busy || !passwordReady} onClick={() => void run(async () => { const nextPreview = await previewSourceTreeConfig(); setPreview(nextPreview); const output = await createSourceTreeConfigBundle(nextPreview.token, createPassword); setResultTitle("sourceTreeConfig.bundleCreated"); setResult(output.bundlePath); setCreatePassword(""); setCreatePasswordConfirmation(""); })}>{t("sourceTreeConfig.create")}</button>
      {preview && <div>{list(preview.files)}{preview.missing.length > 0 && <p>{t("sourceTreeConfig.missing")}: {preview.missing.join(", ")}</p>}</div>}
    </section>
    <section className="backup-preview"><h2>{t("sourceTreeConfig.restore")}</h2><p>{t("sourceTreeConfig.description")}</p><label className="delete-confirmation">{t("sourceTreeConfig.restorePassword")}<input type="password" autoComplete="current-password" disabled={busy} value={restorePassword} onChange={(event) => setRestorePassword(event.target.value)} /></label><p>{t("sourceTreeConfig.legacyPassword")}</p><button disabled={busy} onClick={() => void run(async () => { setInspection(await inspectSourceTreeConfigBundle(restorePassword)); setRecovery(null); setConfirmation(""); setDeleteConfirmation(""); setRestored(false); })}>{t("sourceTreeConfig.inspect")}</button>
      {inspection && <div><p><code>{inspection.bundleName}</code> · SHA-256 ✓</p>{list(inspection.files)}<button disabled={busy} onClick={() => void run(async () => { setRecovery(await previewSourceTreeConfigRecovery(inspection.token, restorePassword)); setConfirmation(""); })}>{t("sourceTreeConfig.recovery")}</button></div>}
      {recovery && <div>{recovery.existingTargets > 0 && <p>{recovery.existingTargets} {t("sourceTreeConfig.existing")}</p>}<label className="delete-confirmation">{t("sourceTreeConfig.confirmation")}<input disabled={busy} value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><button disabled={busy || confirmation !== "RESTORE"} onClick={() => void run(async () => { const output = await recoverSourceTreeConfig(recovery.token, confirmation, restorePassword); setResultTitle("sourceTreeConfig.restored"); setResult(`${output.restored} · ${output.safetyCopyPath}`); setRestorePassword(""); setRestored(true); setRecovery(null); setConfirmation(""); })}>{t("sourceTreeConfig.restore")}</button></div>}
      {inspection && restored && <div><label className="delete-confirmation">{t("sourceTreeConfig.deleteConfirmation")}<input disabled={busy} value={deleteConfirmation} onChange={(event) => setDeleteConfirmation(event.target.value)} /></label><button type="button" className="danger-button" disabled={busy || deleteConfirmation !== "DELETE"} onClick={() => void run(async () => { await deleteSourceTreeConfigBundle(inspection.token, deleteConfirmation); setInspection(null); setDeleteConfirmation(""); })}>{t("sourceTreeConfig.deleteBundle")}</button></div>}
    </section>
    {result && <section className="success-card"><h2>{t(resultTitle)}</h2>{resultTitle === "sourceTreeConfig.bundleCreated" && <><p>{t("sourceTreeConfig.bundlePath")}</p><p><code>{result}</code></p><button disabled={busy} onClick={() => void run(openSourceTreeConfigBundleFolder)}>{t("sourceTreeConfig.openBundleFolder")}</button></>} {resultTitle !== "sourceTreeConfig.bundleCreated" && <p><code>{result}</code></p>}</section>}
    {error && <p role="alert" className="error-banner">{error}</p>}
  </>;
}
